# Generated by Django 3.0.2 on 2020-01-28 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('errdepo_api', '0007_auto_20200121_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(max_length=100)),
                ('fw', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=100)),
                ('fw', models.CharField(max_length=100)),
                ('env', models.TextField()),
                ('errmsg', models.TextField()),
                ('description', models.TextField()),
                ('correspondence', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
